### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by Ambrosiani** [peterk/pimmer#1]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/main.py", line 70, in process
    os.mkdir(target_folder)
FileNotFoundError: [Errno 2] No such file or directory: '/data/jobs/9949ec1286b6a1c9cac8406bfb7bdcfe'
```

docker-compose up -d didn't throw any errors.

**Comment by Ambrosiani** [comment]
I don't know what settings I should use in the .env file, maybe that's the problem?

SMTP_HOST=(my mail host)
SMTP_PORT=587
SMTP_USER=(my mail user)
SMTP_PASSWORD=(my mail password)
FLASK_DEBUG=1
FLASK_KEY=???
ERROR_EMAIL=(my mail)
RMQ_USER=???
RMQ_PASSWORD=???

**Comment by peterk** [comment]
Did you do a git pull of the latest version of the settings example file? Here is a sample .env file you could use.

```
FLASK_DEBUG=1
FLASK_KEY="SS=K#{{!n<d/}jnt,^u#qjA3REFcO>2?~Pn1s>GQoht^#*X-U:WisU*@F"
RMQ_USER=rmq
RMQ_PASSWORD=rmq
```

**Comment by peterk** [comment]
And, if there isn't a folder called data/jobs and data/result in the root folder, please make them. I will make sure they are created in the Dockerfile.

**Comment by Ambrosiani** [comment]
I think that was it, it's running now!

**Comment by peterk** [comment]
Great! I'll close this issue now.
